ImgLabel
friend class Qcorr
Qcorr is a friend class of this ImgLabel class, so all members from ImgLabel are accessible by a Qcorr object.
Qcorr* ImgLabel::m_parentWindow
Pointer to Main Window Object (There should be only one on these).
Referenced by displayCoordinatesOnStatusLabel, ImgLabel.
QRubberBand* ImgLabel::m_rubberBand
the rubberBand object.
Referenced by Qcorr::correlate, Qcorr::disparity, ImgLabel, mouseMoveEvent, mousePressEvent, mouseReleaseEvent, setSelectable.
QPoint ImgLabel::m_originPoint
rubberBand's top-left corner point
Referenced by checkTemplateRegions, mouseMoveEvent, mousePressEvent, mouseReleaseEvent.
QPoint ImgLabel::m_finalPoint
rubberBand's bottom-right corner point
Referenced by checkTemplateRegions, mouseMoveEvent, mouseReleaseEvent.
QPoint ImgLabel::m_currentPressedPoint
the coordinates of the current mouse pointer when it's pressed (held-down)
Referenced by mouseMoveEvent, mousePressEvent.
QPoint ImgLabel::m_labelUpperLeftCornerPoint
Top-left corner of the label.
Referenced by ImgLabel, mouseMoveEvent.
QPoint ImgLabel::m_labelLowerRightCornerPoint
Bottom-right corner of the label.
Referenced by Qcorr::displayImageLabel, mouseMoveEvent.
QPoint ImgLabel::m_mousePosPoint1
First mouse position point of the template selection.
Referenced by mouseMoveEvent, mousePressEvent.
QPoint ImgLabel::m_mousePosPoint2
Final mouse position point of the template selection.
Referenced by mouseMoveEvent.
bool ImgLabel::m_bMouseIsPressed
indicates whether the mouse is currently being pressed (held-down)
Referenced by ImgLabel, mouseMoveEvent, mousePressEvent, mouseReleaseEvent.
bool ImgLabel::m_bStartedTemplateSelection
indicates whether the template selection has begun
Referenced by ImgLabel, mouseMoveEvent, mousePressEvent, mouseReleaseEvent.
bool ImgLabel::m_bMouseInTemplateRegion
indicates whether the mouse pointer is inside the rubberBand selection area
Referenced by checkTemplateRegions, mouseMoveEvent, setTemplateFlags.
bool ImgLabel::m_bMouseAtTemplateTopEdge
indicates whether the mouse pointer is at the top edge of the rubberBand selection area
Referenced by checkTemplateRegions, mouseMoveEvent, setTemplateFlags.
bool ImgLabel::m_bMouseAtTemplateBottomEdge
indicates whether the mouse pointer is at the bottom edge of the rubberBand selection area
Referenced by checkTemplateRegions, mouseMoveEvent, setTemplateFlags.
bool ImgLabel::m_bMouseAtTemplateLeftEdge
indicates whether the mouse pointer is at the left edge of the rubberBand selection area
Referenced by checkTemplateRegions, mouseMoveEvent, setTemplateFlags.
bool ImgLabel::m_bMouseAtTemplateRightEdge
indicates whether the mouse pointer is at the right edge of the rubberBand selection area
Referenced by checkTemplateRegions, mouseMoveEvent, setTemplateFlags.
bool ImgLabel::m_bHasRubberBand
indicates whether the rubberBand is enabled/disabled.
Referenced by displayCoordinatesOnStatusLabel, mouseMoveEvent, mousePressEvent, setSelectable.
int ImgLabel::m_nXNewPos
X-value used in the rubberBand movement.
Referenced by mouseMoveEvent.
int ImgLabel::m_nYNewPos
Y-value used in the rubberBand movement.
Referenced by mouseMoveEvent.
ImgLabel::ImgLabel(Qcorr *parentWindow, QWidget *parent=0)
Constructor of ImgLabel class must point to a Qcorr parentWindow.
References m_bMouseIsPressed, m_bStartedTemplateSelection, m_labelUpperLeftCornerPoint, m_parentWindow, m_rubberBand, setSelectable, setTemplateFlags.
ImgLabel::~ImgLabel()
void ImgLabel::setSelectable(bool bHasRubberBand)
Allows to enable/disable the ImgLabel's rubberBand selection functionality.
bHasRubberBand boolean flag to enable or disable the rubberBand selection functionality.
References m_bHasRubberBand, m_rubberBand.
Referenced by Qcorr::changeMouse, ImgLabel.
void ImgLabel::setTemplateFlags(bool bStatus)
Sets a group of flags used for the mouse pointer in relation to the template's region and edges.
bStatus template region's status
References m_bMouseAtTemplateBottomEdge, m_bMouseAtTemplateLeftEdge, m_bMouseAtTemplateRightEdge, m_bMouseAtTemplateTopEdge, m_bMouseInTemplateRegion.
Referenced by checkTemplateRegions, ImgLabel, mouseMoveEvent.
void ImgLabel::checkTemplateRegions(int mouseX, int mouseY)
Used to check the mouse pointer in relation to the template's region and edges.
mouseX X-coordinates of the mouse pointer mouseY Y-coordinates of the mouse pointer
References m_bMouseAtTemplateBottomEdge, m_bMouseAtTemplateLeftEdge, m_bMouseAtTemplateRightEdge, m_bMouseAtTemplateTopEdge, m_bMouseInTemplateRegion, m_finalPoint, m_originPoint, setTemplateFlags.
Referenced by mouseMoveEvent, mouseReleaseEvent.
void ImgLabel::displayCoordinatesOnStatusLabel(QPoint &point0, QPoint &point1)
Displays the XY-coordinates of the mouse pointer on the status bar Displays the XY-coordinates of the mouse pointer (relative to the ImgLabel) in the status bar of the friend-parent's main window. It only display the mouse pointer coordinate information if rubberBand actions are enabled.
point0 the coordinates of the origin point of the rubberBand selection point1 the coordinates of the final point of the rubberBand selection
References m_bHasRubberBand, m_parentWindow, Qcorr::m_status_label.
Referenced by mouseMoveEvent.
void ImgLabel::mousePressEvent(QMouseEvent *event)
press mouse event handler
References m_bHasRubberBand, m_bMouseIsPressed, m_bStartedTemplateSelection, m_currentPressedPoint, m_mousePosPoint1, m_originPoint, m_rubberBand.
void ImgLabel::mouseMoveEvent(QMouseEvent *event)
move mouse event handler
References checkTemplateRegions, displayCoordinatesOnStatusLabel, m_bHasRubberBand, m_bMouseAtTemplateBottomEdge, m_bMouseAtTemplateLeftEdge, m_bMouseAtTemplateRightEdge, m_bMouseAtTemplateTopEdge, m_bMouseInTemplateRegion, m_bMouseIsPressed, m_bStartedTemplateSelection, m_currentPressedPoint, m_finalPoint, m_labelLowerRightCornerPoint, m_labelUpperLeftCornerPoint, m_mousePosPoint1, m_mousePosPoint2, m_nXNewPos, m_nYNewPos, m_originPoint, m_rubberBand, setTemplateFlags.
void ImgLabel::mouseReleaseEvent(QMouseEvent *event)
release mouse event handler
References checkTemplateRegions, m_bMouseIsPressed, m_bStartedTemplateSelection, m_finalPoint, m_originPoint, m_rubberBand.