ControlsWindow
Ui::ControlsWindowClass ControlsWindow::ui
The Qt GUI form for this class, so its widgets can be accessed and manipulated.
Referenced by ControlsWindow, createActions, setEnableSpinBoxes.
Qcorr* ControlsWindow::m_parentWindow
Pointer to Main Window Object.
Referenced by ControlsWindow, setEnableSpinBoxes, updateParentStatusLabel.
int ControlsWindow::m_nScanInterval
interval of scan traversal by the template
Referenced by ControlsWindow, getScanInterval, setScanInterval, updateParentStatusLabel.
int ControlsWindow::m_nTemplateSize
the template's size (for the width)
Referenced by ControlsWindow, getTemplateSize, setTemplateSize, updateParentStatusLabel.
ControlsWindow::ControlsWindow(Qcorr *parentWindow, QWidget *parent=0)
Constructor of ControlsWindow class must point to a Qcorr parentWindow.
References createActions, m_nScanInterval, m_nTemplateSize, m_parentWindow, setEnableSpinBoxes, ui.
ControlsWindow::~ControlsWindow()
Closes and Destroys itself.
void ControlsWindow::setEnableSpinBoxes(bool bEnable)
Enables/Disables control spinBoxes.
bEnable boolean flag to enable or disable the spinBoxes for controlling correlation parameters of the Qcorr class Set enable spinBoxes including the maximum values based on the m_parentWindow's size of its right image
References m_parentWindow, Qcorr::m_rightImage, ui.
Referenced by Qcorr::changeMouse, ControlsWindow.
int ControlsWindow::getScanInterval()
to obtain the scan Interval set in the spin box
the scan interval value (in pixels)
References m_nScanInterval.
Referenced by Qcorr::disparity, Qcorr::updateStatusLabelWithDisparityInfo.
int ControlsWindow::getTemplateSize()
to obtain the template's size value (as width) set in the spin box
the scan template's size value (in pixels)
References m_nTemplateSize.
Referenced by Qcorr::disparity, Qcorr::updateStatusLabelWithDisparityInfo.
void ControlsWindow::setScanInterval(int nValue)
Q_SLOT that sets scan interval parameter in its friend Qcorr class according to the corresponding spinBox's value.
References m_nScanInterval, updateParentStatusLabel.
Referenced by createActions.
void ControlsWindow::setTemplateSize(int nValue)
Q_SLOT that sets template size parameter in its friend Qcorr class according to the corresponding spinBox's value.
References m_nTemplateSize, updateParentStatusLabel.
Referenced by createActions.
void ControlsWindow::createActions()
Create Signal-Slot connections.
References setScanInterval, setTemplateSize, ui.
Referenced by ControlsWindow.
void ControlsWindow::updateParentStatusLabel()
Updates Parent's status bar with the corresponding values from the control spin boxes.
References m_nScanInterval, m_nTemplateSize, m_parentWindow, Qcorr::m_status_label.
Referenced by setScanInterval, setTemplateSize.