TargetImgLabel
QImage* TargetImgLabel::m_image
the right image (a.k.a target image)
Referenced by paintEvent, setImage.
QImage* TargetImgLabel::m_overlayImage
the overlaid correlation map image
Referenced by overlayImage, paintEvent.
QPoint TargetImgLabel::m_originPoint
the point that indicates the top-left coordinates of the matching rectangle
Referenced by drawEnclosedMatch, paintEvent.
QSize TargetImgLabel::m_rectSize
the size of the enclosing match rectangle
Referenced by drawEnclosedMatch, paintEvent.
int TargetImgLabel::m_nXoffset
X offset for overlay image.
Referenced by overlayImage, paintEvent.
int TargetImgLabel::m_nYoffset
Y offset for overlay image.
Referenced by overlayImage, paintEvent.
bool TargetImgLabel::m_bHasCorrResults
indicates whether correlation results exist so an overlaid image can be composed on top of the target image
Referenced by drawEnclosedMatch, eraseEnclosedMatch, paintEvent, TargetImgLabel.
bool TargetImgLabel::m_bHasImage
indicates whether this TargetImgLabel class has a target (main) image
Referenced by paintEvent, setImage, TargetImgLabel.
bool TargetImgLabel::m_bHasOverlayImage
indicates whether this TargetImgLabel class has an overlaid image (Usually, a correlation results map)
Referenced by eraseEnclosedMatch, overlayImage, paintEvent, setImage, TargetImgLabel.
TargetImgLabel::TargetImgLabel(QWidget *parent=0)
Constructor for the TargetImgLabel class.
References m_bHasCorrResults, m_bHasImage, m_bHasOverlayImage.
TargetImgLabel::~TargetImgLabel()
void TargetImgLabel::setImage(const QImage &labelImage)
Sets background image on this TargetImgLabel class.
labelImage Pointer to a QImage instance that will be used as the label's background
References m_bHasImage, m_bHasOverlayImage, m_image.
Referenced by Qcorr::browseRightImage, Qcorr::changeMouse, Qcorr::correlate, Qcorr::viewMap.
void TargetImgLabel::overlayImage(const QImage &otherImage, int nXoffset=0, int nYoffset=0)
Overlays an Image ontop of the current one.
otherImage Pointer to a QImage instance that will overlay the current one using Qt::CompositionMode_Screen mode nXoffset X offset for overlay image. Default is 0 nYoffset Y offset for overlay image. Default is 0
References m_bHasOverlayImage, m_nXoffset, m_nYoffset, m_overlayImage.
Referenced by Qcorr::viewMap.
void TargetImgLabel::drawEnclosedMatch(const QPoint originPoint, const QSize rectSize)
Draws a dashed, green rectangle to indicate the position of a matching template on the target image.
originPoint A QPoint that indicates the top-left coordinates of the matching rectangle rectSize A QSize for the matching rectangle to be drawn
References m_bHasCorrResults, m_originPoint, m_rectSize.
Referenced by Qcorr::correlate, Qcorr::disparity.
void TargetImgLabel::eraseEnclosedMatch()
Erases the green rectangle that indicated a matching template on the target image.
References m_bHasCorrResults, m_bHasOverlayImage.
Referenced by Qcorr::changeMouse, Qcorr::correlate, Qcorr::disparity.
void TargetImgLabel::paintEvent(QPaintEvent *)
Handles the paint events by refreshing/updating the contents of this TargetImgLabel class.
References m_bHasCorrResults, m_bHasImage, m_bHasOverlayImage, m_image, m_nXoffset, m_nYoffset, m_originPoint, m_overlayImage, m_rectSize.