Qcorr
friend class ImgLabel
the ImgLabel class is a friend of Qcorr in order to make all members of Qcorr accessible by an ImgLabel object
ImgLabel
Referenced by setImageLabels.
friend class ControlsWindow
allows to modify parameters for the correlation operations, such as template size and scan interval. This class is a friend of Qcorr.
ControlsWindow
Referenced by setImageLabels.
int Qcorr::m_nXCorrelationCoordinate
the resulting x-coordinate match obtained from correlation of a template against a target
Referenced by correlate, disparity.
int Qcorr::m_nYCorrelationCoordinate
the resulting y-coordinate match obtained from correlation of a template against a target
Referenced by correlate, disparity.
CorrMethod* Qcorr::m_corrMethodDialog
Dialog Box to choose a correlation method.
Referenced by correlate, setImageLabels.
ControlsWindow* Qcorr::m_controlsWindow
Dialog Box to modify correlation parameters such as template size and scan interval.
Referenced by changeMouse, closeWindows, disparity, setImageLabels, showControlsWindow, updateStatusLabelWithDisparityInfo, ~Qcorr.
QString Qcorr::initialName
String that saves the path for the first file image that has been loaded.
Referenced by browseLeftImage, browseRightImage.
QImage* Qcorr::m_leftImage
Left Panel's Image (a.k.a. "reference image" when performing template matching through correlation).
Referenced by browseLeftImage, correlate, disparity.
QImage* Qcorr::m_rightImage
Right Panel's Image (a.k.a "target image").
Referenced by browseRightImage, changeMouse, correlate, disparity, fileDumpQImage, ControlsWindow::setEnableSpinBoxes, viewMap.
QImage* Qcorr::m_templateImage
Template Image that is selected from the reference image (in the left panel) that will be matched against.
Referenced by correlate, disparity.
QImage* Qcorr::m_corrMapImage
Correlation Map resulting from the Template Matching action.
Referenced by findCorrelation, viewMap.
QImage* Qcorr::m_disparityMapImage
Disparity Map that results from the pixel disparities found between the left and right images.
Referenced by disparity, viewMap.
ImgLabel* Qcorr::m_leftImage_label
label used to display the left image. This is sub-classed widget implemented with the functionality of allowing template selection by a rectangular rubber-band
Referenced by browseLeftImage, changeMouse, correlate, disparity, setImageLabels.
TargetImgLabel* Qcorr::m_targetImage_label
a sub-classed label widget implemented with the purpose of displaying the target image in the right panel with added functionality such as the visualization of the found match
Referenced by browseRightImage, changeMouse, correlate, disparity, setImageLabels, viewMap.
QLabel* Qcorr::m_status_label
status label that updates the mouse-pointer's position coordinates as it moves and selects templates. It also provides other types of information when required.
Referenced by correlate, ImgLabel::displayCoordinatesOnStatusLabel, setImageLabels, ControlsWindow::updateParentStatusLabel, updateStatusLabelWithDisparityInfo.
QVector<QRgb>* Qcorr::m_grayColorTab
8-bit gray-scale color table
Referenced by findCorrelation, setImageLabels.
QVector<QRgb>* Qcorr::m_greenColorTab
8-bit green-scale color table
Referenced by disparity, setImageLabels.
QPoint Qcorr::m_matchingPoint
upper-left corner point where the correlation match was found
Referenced by correlate.
QSize Qcorr::m_templateSize
the current template's size as a QSize object
Referenced by correlate, disparity, updateStatusLabelWithDisparityInfo, viewMap.
QActionGroup* Qcorr::modes_actionGroup
group of menu actions for the mode of operation.
Referenced by setImageLabels.
QDialogButtonBox* Qcorr::m_eStopDialog
A dialogue to stop the current correlation process.
Referenced by abortOperation, correlate, createActions, disparity, setImageLabels, showEStop.
bool Qcorr::m_bHasLeftImage
indicates that an image is loaded in the left panel
Referenced by browseLeftImage, browseRightImage, setImageLabels.
bool Qcorr::m_bHasRightImage
indicates that an image is loaded in the right panel
Referenced by browseLeftImage, browseRightImage, setImageLabels.
bool Qcorr::m_bHasCorrMap
indicates that a correlation map exists
Referenced by changeMouse, correlate, setImageLabels.
bool Qcorr::m_bHasDisparityMap
indicates that a disparity map exists
Referenced by changeMouse, disparity, setImageLabels.
bool Qcorr::m_bEstop
emergency stop for the
Referenced by abortOperation, correlate, disparity, findCorrelation, setImageLabels, showEStop.
int Qcorr::m_nScanInterval
interval of scan traversal by the template
Referenced by disparity, updateStatusLabelWithDisparityInfo.
Qcorr::Qcorr(QWidget *parent=0)
Constructor of the Qcorr class.
References createActions, setImageLabels.
Qcorr::~Qcorr()
Destructor: House keeping that should be done when the Qcorr main window is closed -- specifically, it closes the controlsWindow;.
References m_controlsWindow.
void Qcorr::closeWindows()
Q_SLOT that closes the main Qcorr window and the controls Window;.
References m_controlsWindow.
Referenced by createActions.
void Qcorr::showControlsWindow()
Q_SLOT that shows the controls window and raises it to the foreground if already open.
References m_controlsWindow.
Referenced by createActions.
void Qcorr::browseLeftImage()
Q_SLOT that allows to browse and load an image on the left panel.
References displayImageLabel, initialName, m_bHasLeftImage, m_bHasRightImage, m_leftImage, m_leftImage_label, setEnableActions.
Referenced by createActions.
void Qcorr::browseRightImage()
Q_SLOT that allows to browse and load an image on the right panel.
References initialName, m_bHasLeftImage, m_bHasRightImage, m_rightImage, m_targetImage_label, setEnableActions, TargetImgLabel::setImage, viewMap.
Referenced by createActions.
void Qcorr::changeMouse()
Q_SLOT used to change the mouse pointer according to the current operation mode.
References TargetImgLabel::eraseEnclosedMatch, m_bHasCorrMap, m_bHasDisparityMap, m_controlsWindow, m_leftImage_label, m_rightImage, m_targetImage_label, ControlsWindow::setEnableSpinBoxes, TargetImgLabel::setImage, ImgLabel::setSelectable, updateStatusLabelWithDisparityInfo, viewMap.
Referenced by createActions, setEnableActions.
void Qcorr::viewMap()
Q_SLOT that selectively provides the appropriate existent map of results from correlation (template matching) or pixel disparity.
References m_corrMapImage, m_disparityMapImage, m_rightImage, m_targetImage_label, m_templateSize, TargetImgLabel::overlayImage, TargetImgLabel::setImage.
Referenced by browseRightImage, changeMouse, correlate, createActions, disparity.
void Qcorr::operate()
Q_SLOT that starts the chosen operation according to the mode chosen, either template matching or disparity finder.
References correlate, disparity.
Referenced by createActions.
void Qcorr::abortOperation()
Q_SLOT triggers the flag to abort the current operation.
References m_bEstop, m_eStopDialog.
Referenced by createActions.
void Qcorr::displayImage(QImage *image, QLabel *label)
Displays any QImage on a Qlabel.
image Pointer to a QImage instance label Pointer to a QLabel instance
void Qcorr::displayImageLabel(QImage *image, ImgLabel *label)
Displays the reference image on the left panel's label. which is a sub-classed widget.
image Pointer to a QImage instance label Pointer to a ImgLabel class instance
References ImgLabel::m_labelLowerRightCornerPoint.
Referenced by browseLeftImage.
void Qcorr::createActions()
Sets up actions and Q_SIGNAL-Q_SLOT connections.
References abortOperation, browseLeftImage, browseRightImage, changeMouse, closeWindows, m_eStopDialog, operate, showControlsWindow, viewMap.
Referenced by Qcorr.
void Qcorr::setEnableActions(bool bEnable)
Enables/Disables operation modes actions related widgets.
bEnable boolean flag to enable or disable the operation mode's actions widgets as well as the related widgets such as, start_pushButton and controls_pushButton
References changeMouse.
Referenced by browseLeftImage, browseRightImage.
void Qcorr::setImageLabels()
Instantiates label widgets and initializes other member variables pertinent to the overall GUI functionality of the main window itself.
References ControlsWindow, ImgLabel, m_bEstop, m_bHasCorrMap, m_bHasDisparityMap, m_bHasLeftImage, m_bHasRightImage, m_controlsWindow, m_corrMethodDialog, m_eStopDialog, m_grayColorTab, m_greenColorTab, m_leftImage_label, m_status_label, m_targetImage_label, modes_actionGroup.
Referenced by Qcorr.
void Qcorr::showEStop()
emergency stop to abort the disparity operation process
References m_bEstop, m_eStopDialog.
Referenced by correlate, disparity.
void Qcorr::correlate()
Performs template matching through correlation of the selected template against the target image. It calls findCorrelation() with the appropriate parameters to do a single template correlation across the entire target image.
References TargetImgLabel::drawEnclosedMatch, TargetImgLabel::eraseEnclosedMatch, findCorrelation, CorrMethod::getMethod, m_bEstop, m_bHasCorrMap, m_corrMethodDialog, m_eStopDialog, m_leftImage, m_leftImage_label, m_matchingPoint, m_nXCorrelationCoordinate, m_nYCorrelationCoordinate, m_rightImage, ImgLabel::m_rubberBand, m_status_label, m_targetImage_label, m_templateImage, m_templateSize, TargetImgLabel::setImage, showEStop, viewMap.
Referenced by operate.
void Qcorr::disparity()
Pixel-disparity finding operation. It should be mainly be used with stereo images that can get correlated row-by-row by using findCorrelation() with the pertinent parameters and the appropriate Q_SLOT function implementation.
References TargetImgLabel::drawEnclosedMatch, TargetImgLabel::eraseEnclosedMatch, findCorrelation, ControlsWindow::getScanInterval, ControlsWindow::getTemplateSize, m_bEstop, m_bHasDisparityMap, m_controlsWindow, m_disparityMapImage, m_eStopDialog, m_greenColorTab, m_leftImage, m_leftImage_label, m_nScanInterval, m_nXCorrelationCoordinate, m_nYCorrelationCoordinate, m_rightImage, ImgLabel::m_rubberBand, m_targetImage_label, m_templateImage, m_templateSize, showEStop, updateStatusLabelWithDisparityInfo, viewMap.
Referenced by operate.
float Qcorr::findCorrelation(const unsigned char *imgTarget, const int nWI, const int nHI, const int nDepthI, const unsigned char *imgTemplate, const int nWT, const int nHT, const int nDepthT, int &rnDx, int &rnDy, int nMethod, bool bMultires=false, int nInitialXPosition=0, int nInitialYPosition=0, int nNumberOfRows=0)
Cross-correlation of target image with template image.
Correlation is performed on gray-scale (1 channel image) that are computed in this procedure through the convertToGrayScaleFloat() function. imgTarget Buffer of unsigned characters containing the target image where correlation match is to be found nWI Width of target image nHI Height of target image nDepthI Pixel depth of target image imgTemplate Buffer of unsigned characters containing the template image nWT Width of target image nHT Height of target image nDepthT Pixel depth of target image rnDx x-coordinate where the highest level of correlation match is found (top-left corner of the match) rnDy y-coordinate where the highest level of correlation match is found (top-left corner of the match) nMethod Determines the selected method to be used in the correlation process. The method is a globally defined enumeration. The available methods are: CROSS_CORR (cross correlation): \[ C(u,v) = \frac {\sum{\left\{T(x,y) * I(x-u,y-v)\right\}}} {\sqrt{ \sum{I(x-u,y-v)^2}}} \]SUM_SQ_DIFF (sum of squared differences): \[ C(u,v) = \frac {\sum{\left\{T(x,y)-I(x-u,y-v)\right\}^2}} {\sqrt{\sum{I(x-u,y-v)^2}}} \]CORR_COEFF (correlation coefficient): \[ C(u,v) = \frac {\sum{\left\{(T(x,y)-T_{avg}) * (I(x-u,y-v)-I_{avg})\right\}}} {\sqrt{\sum{(T(x,y)-T_{avg})^2} * \sum{(I(x-u,y-v)-I_{avg})^2}}} \] Remark: The square root of the sum of the squares (RSS) is being used to calculate the aggregate accuracy of a measurement when the accuracies of the all the measuring devices are known. The average accuracy is not merely the arithmetic average of the accuracies (or uncertainties), nor is it the sum of them. Note how the RSS result in this case is greater than the largest of the values under the radical. bMultires Determines if multiresolution correlation should be applied, by making use of image pyramids. With multiresoltion, the correlation can be determined faster than direct correlation. Default is false. nInitialXPosition Indicates the x-coordinate of the pixel on the target image where correlation should start. Default is 0 nInitialYPosition Indicates the y-coordinate of the pixel on the target image where correlation should start. Default is 0 nNumberOfRows Indicates the number of rows on the target image to be scanned. Default is 0, which means all of them. a float array resulting from the conversion of the source image into an 8-bit gray-scale image.
References convertToGrayScaleFloat, m_bEstop, m_corrMapImage, m_grayColorTab.
Referenced by correlate, disparity.
float * Qcorr::convertToGrayScaleFloat(const unsigned char *pchImgOriginalBits, int nSize, int nDepth)
Cast images to an 8-bit gray-scale channel of type float.
pchImgOriginalBits Buffer of unsigned characters as the source image nSize Number of pixels in the source image nDepth Pixel depth of the source image the correlation number computed by method (directly). Additionally, the (dx,dy) offset of the template for which there exists a best match.
Referenced by findCorrelation.
void Qcorr::updateStatusLabelWithDisparityInfo()
Updates Status Bar with Information about parameters for the disparity operation.
References ControlsWindow::getScanInterval, ControlsWindow::getTemplateSize, m_controlsWindow, m_nScanInterval, m_status_label, m_templateSize.
Referenced by changeMouse, disparity.
bool Qcorr::fileDumpQImage(const QString &fileName)
Used for testing and investing the bits stored in QImages or other Qt Widgets.
fileName a QString reference to the file-name as which the raw bits will be storedpchImgOriginalBits Buffer of unsigned characters as the source image true if the bits were properly dumped to the specified fileName
References m_rightImage.