CorrMethod
int CorrMethod::m_nChosenMethod
The selected method in which the correlation "template matching" operation will be based upon. From the global enumeration MethodOfCorrelation, the available correlation methods are: N0_CORR_METHOD = 0, CROSS_CORR = 1, SUM_SQ_DIFF = 2, or CORR_COEFF = 3
Referenced by cancelMethod, chooseMethod, CorrMethod, getMethod.
Ui::CorrMethodClass CorrMethod::ui
The Qt GUI form for this class, so its widgets can be accessed and manipulated.
Referenced by chooseMethod, CorrMethod.
CorrMethod::CorrMethod(QWidget *parent=0)
Constructor for the CorrMethod class.
References cancelMethod, chooseMethod, m_nChosenMethod, ui.
CorrMethod::~CorrMethod()
int CorrMethod::getMethod()
Retrieve the selected method to be used in the correlation process.
Returns the selected method in which the correlation "template matching" operation will be based upon. From the global enumeration MethodOfCorrelation, the available correlation methods are: N0_CORR_METHOD = 0, CROSS_CORR = 1, SUM_SQ_DIFF = 2, or CORR_COEFF = 3selected correlation method (from global enumeration MethodOfCorrelation defined in globals.h). The available correlation methods are: N0_CORR_METHOD = 0, CROSS_CORR = 1, SUM_SQ_DIFF = 2, or CORR_COEFF = 3
References m_nChosenMethod.
Referenced by Qcorr::correlate.
void CorrMethod::cancelMethod()
Q_SLOT to cancel the method selection dialog.
References m_nChosenMethod.
Referenced by CorrMethod.
void CorrMethod::chooseMethod()
Q_SLOT to store the method selection from the dialog.
References m_nChosenMethod, ui.
Referenced by CorrMethod.